#services:
#  db:
#    image: postgres
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    environment:
#     - POSTGRES_DB=shareitdb
#     - POSTGRES_USER=dbuser
#     - POSTGRES_PASSWORD=12345