services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "6541:6541"
    environment:
     - POSTGRES_DB=shareitdb
     - POSTGRES_USER=dbuser
     - POSTGRES_PASSWORD=12345